### ISSUE TITLE
npm package problem

### ISSUE THREAD

**Issue by SANGED** [gsandf/svg-to-ttf#1]
How can i fix that please?
![capture](https://user-images.githubusercontent.com/31478749/42670801-4625a21a-865d-11e8-8609-dc74a044b432.PNG)

**Comment by blakek** [comment]
Hey @SANGED, the first command in the screenshot (`npm install svg-to-ttf`) fails because the package name is wrong (your second command was correct).

The second command (`npm i @gsandf/svg-to-ttf`) is failing because you cannot install a package as a dependency of itself.  It seems you've cloned this repo and tried installing the package from within that clone; that won't work.  If you try running that command in another folder, it should work.

**Comment by blakek** [comment]
Also, I noticed you are using Windows.  We've never tested using any Bash-on-Windows (this package is a bash script), but we'd be interested in knowing how it works.  There's no reason it couldn't be a cross-platform script if it's not already.

**Comment by SANGED** [comment]
@blakek, so wich command i need to Hit: ```npm i @gsandf/svg-to-ttf -g``` ? and where to hit it please?

**Comment by SANGED** [comment]
Working finaly, thank you!!
